### ISSUE TITLE
TODO tacking

### ISSUE THREAD

**Issue by afitz0** [afitz0/flutter_dart_vscode_theme#1]
- [x] Demo files, to see Flutter/Dart code in action
- [x] Generate some screenshots
- [x] Instructions for how to use/install
- [ ] clean up the auto-generated theme files
- [ ] add and tweak the colors for the non-code UI bits
- [ ] fix light mode UI colors (e.g., name of file)
- [ ] adjust orange & pinks to be higher contrast with each other
